var input =document.getElementById('input')
var input2 =document.getElementById('input2')
var input3 =document.getElementById('input3')
var input4 =document.getElementById('input4')
var boton =document.getElementById('boton')